# Generated by Django 4.1.7 on 2023-03-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card', '0004_flashcard_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='category',
        ),
    ]
