# Generated by Django 4.1.7 on 2023-03-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card', '0005_remove_flashcard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='flash_card.category'),
            preserve_default=False,
        ),
    ]
